---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: docker.io/pycontribs/centos:7
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
provisioner:
  name: ansible
verifier:
  name: ansible
